import { AlertTriangle, Check, Copy, Loader2, RefreshCw, ShieldCheck, Sparkles } from "lucide-react";
import { useState, type ReactNode } from "react";
import { Button } from "@/components/ui/button";
import { Label } from "@/components/ui/label";
import { cn } from "@/lib/utils";

export function PageHeader({
  title,
  description,
  eyebrow,
}: {
  title: string;
  description: string;
  eyebrow: string;
}) {
  return (
    <header className="mb-8 max-w-3xl">
      <p className="text-xs font-semibold uppercase tracking-widest text-primary">{eyebrow}</p>
      <h1 className="mt-2 text-3xl sm:text-4xl">{title}</h1>
      <p className="mt-3 text-sm leading-relaxed text-muted-foreground sm:text-base">{description}</p>
    </header>
  );
}

export function InputPanel({ children, onSubmit }: { children: ReactNode; onSubmit: () => void }) {
  return (
    <form
      noValidate
      onSubmit={(e) => {
        e.preventDefault();
        onSubmit();
      }}
      className="surface-card p-5 sm:p-6"
    >
      <div className="mb-5 flex items-center gap-2 border-b border-border pb-4">
        <span className="rounded-md bg-secondary px-2 py-1 text-[11px] font-semibold uppercase tracking-widest text-secondary-foreground">
          Input
        </span>
        <span className="text-xs text-muted-foreground">Information you provide</span>
      </div>
      <div className="space-y-5">{children}</div>
    </form>
  );
}

export function OutputPanel({
  children,
  hasContent,
  loading,
  error,
  onRetry,
  isMock,
  emptyHint,
}: {
  children: ReactNode;
  hasContent: boolean;
  loading: boolean;
  error: string | null;
  onRetry: () => void;
  isMock?: boolean | undefined;
  emptyHint: string;
}) {
  return (
    <section className="ai-surface p-5 sm:p-6" aria-live="polite" aria-busy={loading}>
      <div className="mb-5 flex flex-wrap items-center gap-2 border-b border-gold/40 pb-4">
        <span className="flex items-center gap-1.5 rounded-md bg-primary px-2 py-1 text-[11px] font-semibold uppercase tracking-widest text-primary-foreground">
          <Sparkles className="size-3" aria-hidden="true" /> AI output
        </span>
        <span className="text-xs text-ai-foreground/70">Generated by AI — review before use</span>
        {isMock && (
          <span className="rounded-md bg-gold/40 px-2 py-1 text-[11px] font-semibold text-gold-foreground">
            Demo data
          </span>
        )}
      </div>

      {loading ? (
        <LoadingState />
      ) : error ? (
        <ErrorState message={error} onRetry={onRetry} />
      ) : hasContent ? (
        <div className="space-y-6">{children}</div>
      ) : (
        <p className="py-10 text-center text-sm text-muted-foreground">{emptyHint}</p>
      )}
    </section>
  );
}

export function LoadingState() {
  return (
    <div className="space-y-4 py-2">
      <p className="flex items-center gap-2 text-sm font-medium text-primary">
        <Loader2 className="size-4 animate-spin" aria-hidden="true" /> AI is analyzing your winery
        information...
      </p>
      {[0, 1, 2].map((i) => (
        <div key={i} className="space-y-2">
          <div className="h-3 w-1/3 animate-pulse rounded bg-muted" />
          <div className="h-3 w-full animate-pulse rounded bg-muted" />
          <div className="h-3 w-4/5 animate-pulse rounded bg-muted" />
        </div>
      ))}
    </div>
  );
}

export function ErrorState({ message, onRetry }: { message: string; onRetry: () => void }) {
  return (
    <div className="rounded-lg border border-destructive/40 bg-destructive/5 p-5 text-center">
      <AlertTriangle className="mx-auto size-6 text-destructive" aria-hidden="true" />
      <p className="mt-3 text-sm font-medium text-foreground">{message}</p>
      <Button className="mt-4" variant="outline" onClick={onRetry}>
        Try again
      </Button>
    </div>
  );
}

export function CopyButton({ text, label = "Copy" }: { text: string; label?: string }) {
  const [copied, setCopied] = useState(false);
  return (
    <Button
      type="button"
      variant="outline"
      size="sm"
      onClick={async () => {
        try {
          await navigator.clipboard.writeText(text);
          setCopied(true);
          setTimeout(() => setCopied(false), 1800);
        } catch {
          /* clipboard unavailable */
        }
      }}
    >
      {copied ? (
        <Check className="size-4" aria-hidden="true" />
      ) : (
        <Copy className="size-4" aria-hidden="true" />
      )}
      {copied ? "Copied" : label}
    </Button>
  );
}

export function RegenerateButton({ onClick, disabled }: { onClick: () => void; disabled?: boolean | undefined }) {
  return (
    <Button type="button" variant="outline" size="sm" onClick={onClick} disabled={disabled}>
      <RefreshCw className="size-4" aria-hidden="true" /> Regenerate
    </Button>
  );
}

export function OutputSection({ title, children }: { title: string; children: ReactNode }) {
  return (
    <div>
      <h3 className="text-sm font-semibold uppercase tracking-widest text-primary">{title}</h3>
      <div className="mt-2 text-sm leading-relaxed text-ai-foreground">{children}</div>
    </div>
  );
}

export function BulletList({ items }: { items?: string[] | undefined }) {
  if (!items?.length) return <p className="text-muted-foreground">None identified.</p>;
  return (
    <ul className="space-y-1.5">
      {items.map((item, i) => (
        <li key={i} className="flex gap-2">
          <span className="mt-2 size-1.5 shrink-0 rounded-full bg-gold" aria-hidden="true" />
          <span>{item}</span>
        </li>
      ))}
    </ul>
  );
}

export function VerifyNote({ children }: { children?: ReactNode | undefined }) {
  return (
    <p className="flex items-start gap-2 rounded-lg border border-border bg-card/70 p-3 text-xs leading-relaxed text-muted-foreground">
      <ShieldCheck className="mt-0.5 size-4 shrink-0 text-primary" aria-hidden="true" />
      <span>
        {children ??
          "AI-assisted output, not confirmed fact. For legal, regulatory, labelling, employment, tax, licensing or health and safety matters, confirm with a qualified professional."}
      </span>
    </p>
  );
}

export function Field({
  label,
  required,
  hint,
  htmlFor,
  error,
  children,
}: {
  label: string;
  required?: boolean | undefined;
  hint?: string | undefined;
  htmlFor: string;
  error?: string | undefined;
  children: ReactNode;
}) {
  return (
    <div className="space-y-2">
      <Label htmlFor={htmlFor} className="text-sm font-medium">
        {label}
        {required && (
          <span className="text-destructive" aria-hidden="true">
            *
          </span>
        )}
        {required && <span className="sr-only">(required)</span>}
      </Label>
      {children}
      {hint && !error && <p className="text-xs text-muted-foreground">{hint}</p>}
      {error && (
        <p className="text-xs font-medium text-destructive" role="alert">
          {error}
        </p>
      )}
    </div>
  );
}

export const priorityClass = (p: string) =>
  cn(
    "inline-flex rounded-full px-2 py-0.5 text-[11px] font-semibold",
    p === "Critical" && "bg-destructive/15 text-destructive",
    p === "High" && "bg-primary/15 text-primary",
    p === "Medium" && "bg-gold/35 text-gold-foreground",
    p === "Low" && "bg-muted text-muted-foreground",
  );
